// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Populacao.Connection;

#nullable disable

namespace Populacao.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250424224556_Pessoas")]
    partial class Pessoas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Populacao.Tabela.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GeneroId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GeneroId");

                    b.ToTable("generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Nome = "Masculino"
                        },
                        new
                        {
                            GeneroId = 2,
                            Nome = "Feminino"
                        });
                });

            modelBuilder.Entity("Populacao.Tabela.Pais", b =>
                {
                    b.Property<int>("PaisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaisId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PaisId");

                    b.ToTable("paises");

                    b.HasData(
                        new
                        {
                            PaisId = 1,
                            Nome = "Brasil"
                        },
                        new
                        {
                            PaisId = 2,
                            Nome = "Estados Unidos"
                        },
                        new
                        {
                            PaisId = 3,
                            Nome = "Argentina"
                        },
                        new
                        {
                            PaisId = 4,
                            Nome = "Portugal"
                        },
                        new
                        {
                            PaisId = 5,
                            Nome = "França"
                        },
                        new
                        {
                            PaisId = 6,
                            Nome = "Alemanha"
                        },
                        new
                        {
                            PaisId = 7,
                            Nome = "Japão"
                        },
                        new
                        {
                            PaisId = 8,
                            Nome = "Itália"
                        },
                        new
                        {
                            PaisId = 9,
                            Nome = "Reino Unido"
                        },
                        new
                        {
                            PaisId = 10,
                            Nome = "Canadá"
                        },
                        new
                        {
                            PaisId = 11,
                            Nome = "México"
                        },
                        new
                        {
                            PaisId = 12,
                            Nome = "China"
                        },
                        new
                        {
                            PaisId = 13,
                            Nome = "Índia"
                        },
                        new
                        {
                            PaisId = 14,
                            Nome = "Egito"
                        },
                        new
                        {
                            PaisId = 15,
                            Nome = "África do Sul"
                        },
                        new
                        {
                            PaisId = 16,
                            Nome = "Rússia"
                        },
                        new
                        {
                            PaisId = 17,
                            Nome = "Austrália"
                        },
                        new
                        {
                            PaisId = 18,
                            Nome = "Espanha"
                        },
                        new
                        {
                            PaisId = 19,
                            Nome = "Paquistão"
                        },
                        new
                        {
                            PaisId = 20,
                            Nome = "Indonésia"
                        });
                });

            modelBuilder.Entity("Populacao.Tabela.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PessoaId"));

                    b.Property<int>("GeneroId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaisId")
                        .HasColumnType("integer");

                    b.Property<int>("idade")
                        .HasColumnType("integer");

                    b.HasKey("PessoaId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("PaisId");

                    b.ToTable("pessoas");
                });

            modelBuilder.Entity("Populacao.Tabela.Pessoa", b =>
                {
                    b.HasOne("Populacao.Tabela.Genero", "Genero")
                        .WithMany()
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Populacao.Tabela.Pais", "pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("pais");
                });
#pragma warning restore 612, 618
        }
    }
}
